# Workflow의 이름
# Workflow : 하나의 yml 파일을 하나의 Workflow라고 부른다. 
name: CI/CD using github actions & docker

permissions:
  contents: read

# Event : 실행되는 시점을 설정
# main이라는 브랜치에 push 될 때 아래 Workflow를 실행
on:
  pull_request:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job으로 구성된다. 
# 여러 Job은 기본적으로 병렬적으로 수행된다.
jobs:
  # Job을 식별하기 위한 id
  CI:
    # Github Actions를 실행시킬 서버 종류 선택
    runs-on: ubuntu-latest
    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps:
      - name: get github repository
        uses: actions/checkout@v3

      - name: Check gradlew existence
        run: ls -l ./gradlew

      # jdk 버전 setting
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin # 어떤 브랜드를 쓸거냐
          java-version: 17

      # radle caching - 빌드 시간 향상
      - name: Gradle Caching 
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
